# docker-compose.yml
version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./:/usr/src/service:delegated
       - /node_modules
     ports:
       - 3000:3000
     environment:
       - WATCHPACK_POLLING=true